# Page settings

baseurl = "http://example.org/"
languageCode = "en-us"
title = "John Doe Resume"
theme = "hugo-orbit-theme"
googleAnalytics = "UA-XXXXXXX-Y"

# Do not build files for websites. Need them? Set to false
disableRSS = true
disableSitemap = true
disable404 = true

[params]

# Meta
    description = "Hugo Responsive Resume/CV Theme for Developers"
    author = "Pavel Kanyshev"

# Theme styles

    # The original template comes with 6 colour schemes. You may choose styles below.
    # "styles.css", "styles-2.css", "styles-3.css", "styles-4.css", "styles-5.css", "styles-6.css"
    # are available. Also the source LESS files are included so
    # it’s quick and easy to change the styling and colour scheme.

    styles = "styles-6.css"

# Sidebar sections

    # Profile section
    [params.profile]
        name = "Rhiski Aprilianto"
        tagline = "Civil Engineer"
        avatar = "profile.png"

    # Contact section
    [params.contact]
        enable = true

        [[params.contact.list]]
        class = "email"
        icon = "fa-envelope"
        url = "mailto: mail@rhiskiapril.com"
        title = "mail@rhiskiapril.com"

        [[params.contact.list]]
        class = "website"
        icon = "fa-globe"
        url = "//rhiskiapril.com"
        title = "rhiskiapril.com"

        [[params.contact.list]]
        class = "linkedin"
        icon = "fa-linkedin"
        url = "//linkedin.com/in/rhiski-aprilianto-048323139"
        title = "Rhiski Aprilianto"

    # Education section
    [params.education]
        enable = true
        title = "Education"

        [[params.education.list]]
        degree = "D3 Civil Engineer"
        college = "State Polytechnic of Malang"
        dates = "2014 - 2017"

    # Languages section
    [params.language]
        enable = true
        title = "Languages"

        [[params.language.list]]
        language = "Javanese"
        level = "Native"

        [[params.language.list]]
        language = "Bahasa"
        level = "Native"

        [[params.language.list]]
        language = "English"
        level = "Professional"

    # Interests section
    [params.interests]
        enable = true
        title = "Interests"

        [[params.interests.list]]
        interest = "Archery"

        [[params.interests.list]]
        interest = "Reading"

# Main body sections

    # You may use markdown in summary, details and intro fields. But don't overdose, it's resume!:)

    # Summary section
    [params.summary]
        enable = true
        icon = "fa-user"
        title = "Career Profile"
        summary = "I have worked at the flat project as a Quality Control and now work as an Junior Structure Engineer in a Structural Consulting Office"

    # Experiences section
    [params.experiences]
        enable = true
        icon = "fa-briefcase"
        title = "Experiences"

        [[params.jobs.list]]
        position = "Junior Structure Engineer"
        dates = "Aug 2018 - Present"
        company = "Pusaka Desain, Kediri"
        details = "My Job Descriptions:\n\n1. Prepare reports, designs and drawings.\n2. Make calculations about pressures, loads and stresses.\n3. Consider the strength of construction materials and select appropriately."

        [[params.jobs.list]]
        position = "Quality Control"
        dates = "Oct 2017 - Mar 2018"
        company = "KSO Adhi Karya - Jaya Konstruksi - Penta Architecture, Jakarta"
        details = "To ensures proper quality of the materials, methods of execution, maintains guidelines of contract standards and makes sure work progresses according to it."

    # Projects section
    [params.projects]
        enable = true
        icon = "fa-archive"
        title = "Projects"
        intro = "**Some projects that I have worked on**"
        [[params.projects.list]]
        title = "Proyek Rusun Nagrak Tower 6-10"
        url = "https://www.google.com/maps/place/Flat+Project+Nagrak/@-6.1271418,106.9567785,15z/data=!4m5!3m4!1s0x0:0x4dc69de51919f648!8m2!3d-6.1271418!4d106.9567785"
        tagline = "as Quality Control"


    # Skills section
    [params.skills]
        enable = true
        icon = "fa-rocket"
        title = "Skills & Proficiency"

        [[params.skills.list]]
        skill = "SAP2000"
        level = "90%"
                
        [[params.skills.list]]
        skill = "Staad.Pro"
        level = "85%"

        [[params.skills.list]]
        skill = "Ms. Project"
        level = "80%"

        [[params.skills.list]]
        skill = "Ms. Office"
        level = "90%"

        [[params.skills.list]]
        skill = "Autocad"
        level = "85%"

        [[params.skills.list]]
        skill = "Reincforment Concrete Design"
        level = "85%"
		
		[[params.skills.list]]
        skill = "Steel Structure Design"
        level = "80%"
		
		[[params.skills.list]]
        skill = "Seismic Design"
        level = "75%"

    # Footer section

    # The original template is released under the Creative Commons Attribution 3.0 License.
    # Please keep the original attribution link when using for your own project.
    # If you'd like to use the template without the attribution,
    # you can check out other license options via template author's website: themes.3rdwavemedia.com
    # 
    # As for Hugo port you may rewrite the "Ported for..." line with setting your name below.

    [params.footer]
        copyright = ""
